### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by sparanoid** [klorenz/atom-character-table#9]
[Enter steps to reproduce below:]

1. In an existing Markdown document
2. alt - L, type `copyright` and press enter

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [character-table](https://github.com/klorenz/atom-character-table) package, v0.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'split' of undefined
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:459:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:745:29
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2037:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1999:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:19)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at CharacterTableView.module.exports.CharacterTableView.confirmed (/Users/sparanoid/.atom/packages/character-table/lib/character-table-view.coffee:272:42)
  at CharacterTableView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:28.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:28 character-table:toggle (atom-text-editor.editor.is-focused)
  3x -0:25 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:21.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:17.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:11.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 character-table:toggle (atom-text-editor.editor.is-focused)
  2x -0:03.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "~/Git"
  },
  "character-table": {}
}
```

### Installed Packages

```coffee
# User
character-table, v0.4.2
color-picker, v2.0.12
editor-stats, v0.17.0
editorconfig, v1.2.0
html-entities, v0.4.0
language-liquid, v0.4.0
minimap, v4.13.3
pangu, v0.2.0
pigments, v0.15.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by sparanoid** [comment]
:+1:
